stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME_WEB: "kalax1011/web-app"
  DOCKER_IMAGE_NAME_APP: "kalax1011/worker-vote"
  DOCKER_IMAGE_NAME_RESULTS: "kalax1011/results-app"
  DOCKER_IMAGE_TAG: "latest"
  DOCKER_REGISTRY_URL: "docker.io"


#before_script:

#  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD --password-stdin $DOCKER_REGISTRY_URL

build-web-app:       # This job runs in the build stage, which runs first.
  stage: build
  image: docker:latest
  script:
    - docker build -t  $DOCKER_IMAGE_NAME_WEB:$DOCKER_IMAGE_TAG ./web-vote-app

build-vote-worker:       # This job runs in the build stage, which runs first.
  stage: build
  image: docker:latest
  script:
    - docker build -t $DOCKER_IMAGE_NAME_APP:$DOCKER_IMAGE_TAG ./vote-worker

build-results-app:       # This job runs in the build stage, which runs first.
  stage: build
  image: docker:latest
  script:
    - docker build -t $DOCKER_IMAGE_NAME_RESULTS:$DOCKER_IMAGE_TAG ./results-app

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
