#
# Compose file to run the voting app and dependent services
#

version: '2'

services:
  web-vote-app:
    image: web-vote
    environment:
      WEB_VOTE_NUMBER: "01"
      constraint:node: "=frontend01"
    expose:
      - "8081:80" 

  vote-worker:
    image: worker-vote
    environment:
      FROM_REDIS_HOST: 1
      TO_REDIS_HOST: 1

  results-app:
    image: result-app
    expose:
      - "8082:80"

  redis01:
    image: redis:3
    expose: 
      - "6379:6379" 


  store:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg8675309
